version: '3.8'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AnimalShelter
    ports:
      - 5432:5432
    networks:
      - corpbot-network

networks:
  corpbot-network:
    driver: bridge